# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created: Mon Jul  7 20:57:33 2014
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(337, 589)
        self.verticalLayout_2 = QtGui.QVBoxLayout(Form)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.pointsTableWidget = QtGui.QTableWidget(Form)
        self.pointsTableWidget.setObjectName(_fromUtf8("pointsTableWidget"))
        self.pointsTableWidget.setColumnCount(2)
        self.pointsTableWidget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.pointsTableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.pointsTableWidget.setHorizontalHeaderItem(1, item)
        self.horizontalLayout_3.addWidget(self.pointsTableWidget)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.addPushButton = QtGui.QPushButton(Form)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.addPushButton.setFont(font)
        self.addPushButton.setText(_fromUtf8(""))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("icons/1403292182_Add.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.addPushButton.setIcon(icon)
        self.addPushButton.setObjectName(_fromUtf8("addPushButton"))
        self.verticalLayout.addWidget(self.addPushButton)
        self.delPushButton = QtGui.QPushButton(Form)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.delPushButton.setFont(font)
        self.delPushButton.setText(_fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("icons/1403362103_Delete.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.delPushButton.setIcon(icon1)
        self.delPushButton.setObjectName(_fromUtf8("delPushButton"))
        self.verticalLayout.addWidget(self.delPushButton)
        spacerItem = QtGui.QSpacerItem(20, 30, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem)
        self.savePushButton = QtGui.QPushButton(Form)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.savePushButton.setFont(font)
        self.savePushButton.setText(_fromUtf8(""))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8("icons/1404769242_Download.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.savePushButton.setIcon(icon2)
        self.savePushButton.setObjectName(_fromUtf8("savePushButton"))
        self.verticalLayout.addWidget(self.savePushButton)
        self.loadPushButton = QtGui.QPushButton(Form)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.loadPushButton.setFont(font)
        self.loadPushButton.setText(_fromUtf8(""))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8("icons/1404769249_Upload.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.loadPushButton.setIcon(icon3)
        self.loadPushButton.setObjectName(_fromUtf8("loadPushButton"))
        self.verticalLayout.addWidget(self.loadPushButton)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label = QtGui.QLabel(Form)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_2.addWidget(self.label)
        self.methodsComboBox = QtGui.QComboBox(Form)
        self.methodsComboBox.setObjectName(_fromUtf8("methodsComboBox"))
        self.methodsComboBox.addItem(_fromUtf8(""))
        self.methodsComboBox.addItem(_fromUtf8(""))
        self.methodsComboBox.addItem(_fromUtf8(""))
        self.methodsComboBox.addItem(_fromUtf8(""))
        self.methodsComboBox.addItem(_fromUtf8(""))
        self.horizontalLayout_2.addWidget(self.methodsComboBox)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.countPushButton = QtGui.QPushButton(Form)
        self.countPushButton.setObjectName(_fromUtf8("countPushButton"))
        self.horizontalLayout.addWidget(self.countPushButton)
        self.exitPushButton = QtGui.QPushButton(Form)
        self.exitPushButton.setObjectName(_fromUtf8("exitPushButton"))
        self.horizontalLayout.addWidget(self.exitPushButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout)

        self.retranslateUi(Form)
        QtCore.QObject.connect(self.exitPushButton, QtCore.SIGNAL(_fromUtf8("clicked()")), Form.close)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtGui.QApplication.translate("Form", "Кластерный анализ", None, QtGui.QApplication.UnicodeUTF8))
        self.pointsTableWidget.setToolTip(QtGui.QApplication.translate("Form", "<html><head/><body><p>Точки</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        item = self.pointsTableWidget.horizontalHeaderItem(0)
        item.setText(QtGui.QApplication.translate("Form", "x", None, QtGui.QApplication.UnicodeUTF8))
        item = self.pointsTableWidget.horizontalHeaderItem(1)
        item.setText(QtGui.QApplication.translate("Form", "y", None, QtGui.QApplication.UnicodeUTF8))
        self.addPushButton.setToolTip(QtGui.QApplication.translate("Form", "<html><head/><body><p>Добавить точку</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.delPushButton.setToolTip(QtGui.QApplication.translate("Form", "<html><head/><body><p>Удалить точку</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.savePushButton.setToolTip(QtGui.QApplication.translate("Form", "<html><head/><body><p>Сохранить точки в файл</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.savePushButton.setWhatsThis(QtGui.QApplication.translate("Form", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.loadPushButton.setToolTip(QtGui.QApplication.translate("Form", "<html><head/><body><p>Загрузить точки из файла</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.loadPushButton.setWhatsThis(QtGui.QApplication.translate("Form", "load", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Form", "Метод:", None, QtGui.QApplication.UnicodeUTF8))
        self.methodsComboBox.setToolTip(QtGui.QApplication.translate("Form", "<html><head/><body><p>Выберите метод кластеризации</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.methodsComboBox.setItemText(0, QtGui.QApplication.translate("Form", "Последовательная кластеризация", None, QtGui.QApplication.UnicodeUTF8))
        self.methodsComboBox.setItemText(1, QtGui.QApplication.translate("Form", "Кинга", None, QtGui.QApplication.UnicodeUTF8))
        self.methodsComboBox.setItemText(2, QtGui.QApplication.translate("Form", "К-средних", None, QtGui.QApplication.UnicodeUTF8))
        self.methodsComboBox.setItemText(3, QtGui.QApplication.translate("Form", "\"Форель\"", None, QtGui.QApplication.UnicodeUTF8))
        self.methodsComboBox.setItemText(4, QtGui.QApplication.translate("Form", "\"Краб\"", None, QtGui.QApplication.UnicodeUTF8))
        self.countPushButton.setToolTip(QtGui.QApplication.translate("Form", "<html><head/><body><p>Выполнить кластеризацию и отобразить результаты</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.countPushButton.setText(QtGui.QApplication.translate("Form", "Рассчитать", None, QtGui.QApplication.UnicodeUTF8))
        self.exitPushButton.setToolTip(QtGui.QApplication.translate("Form", "<html><head/><body><p>Выйти из программы</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.exitPushButton.setText(QtGui.QApplication.translate("Form", "Выход", None, QtGui.QApplication.UnicodeUTF8))

